config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :sections, except: [:new]
  resources :chapters, except: [:index, :new] do
    resources :topics, except: [:index]
  end
  resources :messages, except: [:show, :new]
  resources :likes, only: [:create]


  root 'sections#index'
  get 'admins/index'
  post 'users/create_user'
  match '*path', :to => 'application#routing_error', :via => [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord

  has_many :messages, dependent: :destroy

  accepts_nested_attributes_for :messages

  # Снова имя и какая-то магия
  def answers
    topic_id = self.id
    all_messages = messages_by_topic_id(topic_id).count
    all_messages - 1 if all_messages > 0
  end

  def topic_author
    user_by_id(self.user_id)
  end

  # Очень напоминает такой же код из chapter.rb
  def last_post
    last_message = last_topic_message
    last_post_info = {message: last_message.try(:posted)}
    user_id = last_message.try(:user_id)
    user = user_by_id(user_id) if user_id
    last_post_info[:user] = user
    last_post_info[:user_name] = user.try(:user_name)
    return last_post_info
  end

  # Это должно быть в ability
  def editable?(current_user)
    (self.answers == 0 && current_user.try(:id).equal?(self.user_id)) || current_user.try(:admin)
  end

  private

  def user_by_id user_id
    User.find(user_id)
  end

  def last_topic_message
    topic_id = self.id
    messages_by_topic_id(topic_id).order(created_at: :asc).last
  end

  def messages_by_topic_id(topic_id)
    Message.where(topic_id: topic_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!, only: [:create, :new]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :set_section, only: [:new, :show, :edit]
  before_action :only_topic_fetch, only: [:create, :update]


  PAGINATION_LIMIT = 10.freeze

  # GET /topics
  # GET /topics.json
  def index; end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @message = Message.new()
    @like = Like.new()
    messages = @topic.messages
    # Снова ActiveRecord. Плюс я видел уже этот код, за небольшим изменением в chapters_controller
    messages = messages.where('text like ?', "%#{params[:text]}%") if params[:text]
    @messages = messages.order(created_at: :asc).paginate(page: params[:page], per_page: PAGINATION_LIMIT)
  end

  # GET /topics/new
  def new
    @topic = Topic.new()
    @message = Message.new()
  end

  # GET /topics/1/edit
  def edit; end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        @message = Message.new(message_params)
        unless @message.save
          format.html { render :new }
          format.json { render json: @topic.errors, status: :unprocessable_entity }
        end
        format.html { redirect_to chapter_topic_path(current_chapter, @topic), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to chapter_topic_path(current_chapter, @topic), notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to chapter_path(current_chapter), notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      @topic_params.except(:message).merge(internal_topic_params).permit!
    end

    def internal_topic_params
      {chapter_id: current_chapter, user_id: current_user.id, status: Constant::STATUS }
    end

    def message_params
      external_message_params = @topic_params.fetch(:message, {})
      internal_message_params = {topic_id: @topic.id, chapter_id: current_chapter,
                                 user_id: current_user.id, status: Constant::STATUS, order: 1}
      external_message_params.merge(internal_message_params).permit!
    end

    def only_topic_fetch
      @topic_params = params.fetch(:topic, {})
    end

    def current_chapter
      params.fetch(:chapter_id, {})
    end

    def set_section
      @chapter = Chapter.find(params[:chapter_id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_edit_form.html.erb
<div class="panel-body-chapter">
  <%= form_with(model: [chapter, topic], local: true) do |form| %>
      <div class="form-group">
        <%= form.label :topic_title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_field :description, class: 'form-control' %>
      </div>
      <div class="actions ">
        <%= form.submit class: 'btn btn-primary'%>
      </div>
      <% if topic.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

            <ul>
              <% topic.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
  <% end %>
</div>

app/views/topics/_form.html.erb
<div class="panel-body-chapter">
  <%= form_with(model: [chapter, topic], local: true) do |form| %>
    <div class="form-group">
      <%= form.label :topic_title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>
      <% if request[:action] != 'edit' %>
        <div class="form-group">
          <%= form.fields_for message do |g| %>
            <%= g.trix_editor :text %>
          <% end %>
        </div>
      <%end%>
    <div class="actions ">
      <%= form.submit class: 'btn btn-primary'%>
    </div>
    <% if topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

        <ul>
          <% topic.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

app/views/topics/_like_form.html.erb
<%= form_for @like, remote: true, html: { :id => "new_like_#{message.id}" } do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :message_id, value: message.id %>
    <%= f.hidden_field :author_id, value: message.author.id %>
  <%= f.button :submit do %>
    <span class="glyphicon glyphicon-thumbs-up"></span> Like
  <% end %>
<% end %>

app/views/topics/_likes.html.erb
<div class="row">
 <div class="col-sm-4">likes:</div>
 <div id="message-<%=message_id%>" class="col-sm-4">
   <%= likes.try(:count) %>
 </div>

</div>

app/views/topics/_message.html.erb
<div class="forum-section">
  <table class="table">
    <thead class="forum-title">
    <tr>
      <th class="col-sm-2">
        <%= link_to message.author_user_name, user_path(message.user_id), class: 'forum-title' %>
      </th>
      <th class="col-sm-9"><%= message.posted %>
        <% if editable %>
          | <%= link_to 'Edit', edit_message_path(message), data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
          | <%= link_to 'Delete', message_path, method: :delete, class: 'forum-title' %>
        <% end %>
      </th>
      <th class="col-sm-1"></th>
    </tr>
    </thead>
    <tbody class="forum-section-white">
    <tr>
      <td class="col-sm-2">
        <div class="col-sm-12"><%= image_tag message.author_avatar%></div>
        <div class="col-sm-12"><%= message.user_author %></div>
        <div class="col-sm-12">messages: <%= message.all_by_author %></div>
        <div class="col-sm-12">from: <%= message.author_address %></div>
      </td>
      <td class="col-sm-9"><%= message.text.html_safe %></td>
      <td class="col-sm-2">
        <%= render 'likes', likes: message.likes, message_id: message.id%>
        <% if user_signed_in? && !message.likes.map(&:user_id).include?(current_user.id) &&
            !current_user.id.equal?(message.user_id)  %>
            <%= render 'like_form', message: message %>
        <% end %>
        <button type="button" class="btn btn-default quotes">Quotes</button>
      </td>
    </tr>
    <% if message.status != Constant::STATUS %>
        <tr>
          <td></td>
          <td class="updated"><%= message.status %><%= message.updated %></td>
          <td></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/topics/_message_form.html.erb
<div class="panel-body-chapter">
  <%= form_with(model: message, local: true) do |form| %>
    <div class="form-group">
      <%= form.trix_editor :text %>
    </div>
    <%= form.hidden_field :chapter_id, value: chapter.id %>
    <%= form.hidden_field :topic_id, value: topic.id %>
    <div class="actions ">
      <%= form.submit class: 'btn btn-primary'%>
    </div>
    <% if message.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(message.errors.count, "error") %> prohibited this topic from being saved:</h2>
        <ul>
          <% message.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

app/views/topics/_topic.html.erb
<tr>
  <td class="col-sm-7">
    <%= link_to topic.title, chapter_topic_path(topic.chapter_id, topic), class: 'chapter-head' %>
    <div class="chapter-description"><%= topic.description %></div>
  </td>
  <td class="col-sm-1"><%= topic.answers %></td>
  <td class="col-sm-2"><%= link_to topic.topic_author.user_name, topic.topic_author %></td>
  <td class="col-sm-2">
    <% last_post = topic.last_post%>
    <%=last_post[:message]%>
    <%= link_to last_post[:user_name], last_post[:user] if last_post[:user]%>
  </td>
</tr>

app/views/topics/edit.html.erb
<div class="container">
  <div class="forum-section">
    <div class="forum-title">
      <h1>Editing Topic</h1>
    </div>
    <div class="forum-section-white">
      <%= render 'form', topic: @topic, chapter: @chapter, message: @message %>
    </div>
  </div>

  <%= link_to 'Back', chapter_topic_path(@chapter.id, @topic.id) %>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="forum-section">
      <div class="forum-title">
        <h1>New Topic</h1>
      </div>
      <div class="forum-section-white">
        <%= render 'form', topic: @topic, chapter: @chapter, message: @message %>
      </div>
  </div>

  <%= link_to 'Back', chapter_path(@chapter.id) %>
</div>

app/views/topics/show.html.erb
<%= javascript_include_tag 'topics/quotes' %>

<div class="container">
  <p id="notice"><%= notice %></p>
  <form action="<%= chapter_topic_path(@chapter, @topic) %>" method="get">
    <%= text_field_tag :text, params[:text] %>
    <%= submit_tag 'Find message with...', class: 'btn btn-default' %>
  </form>
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @messages %>
    </div>
    <%= will_paginate @messages, :container => false, renderer: BootstrapPagination::Rails %>
  </div>
  <div class="forum-section">
    <div class="forum-title"><%=@topic.title%>
    <% if @topic.editable?(current_user)%>
      | <%= link_to 'Edit Topic', edit_chapter_topic_path(@chapter, @topic), data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
      | <%= link_to 'Delete Topic', chapter_topic_path(@chapter, @topic), method: :delete, data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
    <% end %>
    </div>
  </div>
  <% @messages.each do |message| %>
    <%= render 'message', message: message, editable: @topic.editable?(current_user)%>
  <% end %>
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @messages %>
    </div>
    <%= will_paginate @messages, :container => false, renderer: BootstrapPagination::Rails %>
  </div>
  <div class="forum-section">
    <div class="forum-title">Answer</div>
    <div class="forum-section-white">
      <%= render 'message_form', topic: @topic, chapter: @chapter, message: @message %>
    </div>
  </div>
  <%= link_to 'Back', chapter_path(@chapter) %>
</div>