config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :sections, except: [:new]
  resources :chapters, except: [:index, :new] do
    resources :topics, except: [:index]
  end
  resources :messages, except: [:show, :new]
  resources :likes, only: [:create]


  root 'sections#index'
  get 'admins/index'
  post 'users/create_user'
  match '*path', :to => 'application#routing_error', :via => [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :large => "400x400>", :medium => "200x200>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :likes

  # почему админ integer? почему просто не определить его boolean и использовать рельсовый admin? И это код для view?
  def group
    self.admin == 1 ? 'Administrator' : 'User'
  end

  # Форматирование представления данных - работа View слоя. Это код хелперов, ника не модели
  def registered
    self.created_at.strftime('%v %T')
  end

  # Аналогично
  def birthdate
    self.birth_date.strftime('%v') if self.birth_date
  end

  # где ассоциации? имя метода некорректно, метод возвращаяет count, а не коллекцию
  # has_many :messages
  # delegate :count, to: :message, prefix: true
  # и на выходе получим message_count метод.
  # А в идеале такие вещи решаются просто использованием counter_cache
  def all_by_author
    Message.where(user_id: self.id).count
  end

  # Та же претензия.
  # Зачем здесь try?
  def likes_count
    Like.where(author_id: self.id).try(:count)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include AdminsHelper

  before_action :authenticate_user!
  before_action :authenticate_admin, only:[:edit, :update, :destroy, :new, :create_user]
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  PAGINATION_LIMIT = 10.freeze
  MESSAGE_PAGINATION_LIMIT = 3.freeze

  def index
    @users = User.order(user_name: :asc).paginate(page: params[:page], per_page: PAGINATION_LIMIT)
  end

  def show
    @chapters = Chapter.all
    @chapter = params[:chapter_id]
    # Опять
    topics = Topic.joins(:messages).where(messages:{user_id: @user.id}).distinct
    topics = topics.where(chapter_id: params[:chapter_id]) if @chapter && @chapter.present?
    @topics = topics.order(updated_at: :desc).paginate(page: params[:page], per_page: MESSAGE_PAGINATION_LIMIT)
  end

  def new
    @user = User.new
  end

  def create_user
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user.id), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user.toggle :admin if can? :manage, @user
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to user_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.fetch(:user, {}).permit!
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row centered-form">
    <div class="col-xs-8 col-sm-8 col-md-4 col-sm-offset-4 col-md-offset-4">
      <p id="notice"><%= notice %></p>
      <div class="panel panel-default devise-bs">
        <div class="panel-heading">
          <h4>Edit <%= @user.user_name %></h4>
        </div>
        <div class="panel-body">
          <%= form_for(@user, local: true) do |f| %>
            <div class="form-group">
              <%= f.label :admin %><br />
              <%= f.check_box(:admin, as: :boolean, checked_value: 1, unchecked_value: 0) %>
            </div>
            <div class="form-group">
              <%= f.label t('devise.passwords.first_name', default: 'First name') %><br />
              <%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label t('devise.passwords.last_name', default: 'Last name') %><br />
              <%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label t('devise.passwords.user_name', default: 'User name') %><br />
              <%= f.text_field :user_name, autofocus: true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label t('devise.passwords.gender', default: 'Gender') %><br />
              <%= f.select(:gender, %w[Male Female], {autofocus: true}, class: 'form-control') %>
            </div>
            <div class="form-group">
              <%= f.label t('devise.passwords.address', default: 'Address') %><br />
              <%= f.text_field :address, autofocus: true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label t('devise.passwords.birth_date', default: 'Birthdate') %><br />
              <%= f.datetime_select(:birth_date, {start_year: 1930, end_year: Time.now.year, discard_hour: true}, class: 'form-control birth')%>
            </div>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, autofocus: true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= image_tag @user.avatar.url(:thumb)%>
              <%= f.file_field :avatar, class: 'filestyle' %>
            </div>
            <div class="actions">
              <%= f.submit "Update", class: 'btn btn-primary' %>
            </div>
          <% end %>
          <br />
          <%= link_to "Back", :back %>
          <% if @user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    $(":file").filestyle({btnClass: "btn-danger"});
</script>

app/views/users/index.html.erb
<div class="container">
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false, renderer: BootstrapPagination::Rails %>
  </div>
  <div class="forum-section">
    <table class="table">
      <thead class="forum-title">
      <tr>
        <th class="col-sm-4">Username
          <% if user_admin? %>
            | <%= link_to 'New User', new_user_path, class: 'forum-title' %>
          <% end%>
        </th>
        <th>Group</th>
        <th>Registered</th>
        <th>Email</th>
      </tr>
      </thead>
      <tbody class="forum-section-white">
      <% @users.each do |user| %>
        <tr>
          <td class="col-sm-4"><%= link_to user.user_name, user %></td>
          <td><%= user.group %></td>
          <td><%= user.registered %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to 'Back', sections_path %>
</div>

app/views/users/new.html.erb
<script type="text/javascript" src="http://www.clubdesign.at/floatlabels.js"></script>
<div class="container">
  <div class="row centered-form">
    <div class="col-xs-8 col-sm-8 col-md-4 col-sm-offset-4 col-md-offset-4">
      <p id="notice"><%= notice %></p>
      <div class="panel panel-default devise-bs">
        <div class="panel-heading">
          <h4><%= t('.sign_up', default: 'Sign up') %></h4>
        </div>
        <div class="panel-body">
          <%= form_for(@user,:url => url_for(:controller => 'users', :action => 'create_user'), local: true) do |f| %>
              <div class="form-group">
                <%= f.label t('devise.passwords.first_name', default: 'First name') %><br />
                <%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label t('devise.passwords.last_name', default: 'Last name') %><br />
                <%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label t('devise.passwords.user_name', default: 'User name') %><br />
                <%= f.text_field :user_name, autofocus: true, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label t('devise.passwords.gender', default: 'Gender') %><br />
                <%= f.select(:gender, %w[Male Female], {autofocus: true}, class: 'form-control') %>
              </div>
              <div class="form-group">
                <%= f.label t('devise.passwords.address', default: 'Address') %><br />
                <%= f.text_field :address, autofocus: true, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label t('devise.passwords.birth_date', default: 'Birthdate') %><br />
                <%= f.datetime_select(:birth_date, {start_year: 1930, end_year: Time.now.year, discard_hour: true}, class: 'form-control birth')%>
              </div>
              <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, autofocus: true, class: 'form-control' %>
              </div>
              <div class="form-group image-upload">
                <%= f.label :attach_avatar %>
                <label for="file-input">
                  <span class="glyphicon glyphicon-camera"></span>
                </label>
                <%= f.file_field :avatar, id: 'file-input' %>
              </div>
              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
              </div>
              <%= f.submit 'New user', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
      <%= link_to "Back", :back %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-5">
      <div class="forum-section">
        <div class="forum-title">
          Profile
          <% if current_user.id.equal?(@user.id)%>
            | <%= link_to 'Edit', edit_user_registration_path, class: 'forum-title' %>
          <% elsif user_admin?%>
            | <%= link_to 'Edit', edit_user_path, data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
            | <%= link_to 'Delete User', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
          <% end %>
        </div>
        <div class="forum-section-white">
          <div class="panel-body">
            <div class="col-md-12 centered">
              <%= image_tag @user.avatar.url(:medium)%>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag t('devise.passwords.user_name', default: 'User name') %><br />
            </div>
            <div class="col-md-8">
              <%= @user.user_name%>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag t('devise.passwords.first_name', default: 'First name') %>
            </div>
            <div class="col-md-8">
              <%= @user.first_name %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag t('devise.passwords.last_name', default: 'Last name') %>
            </div>
            <div class="col-md-8">
              <%= @user.last_name %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag t('devise.passwords.gender', default: 'Gender') %><br />
            </div>
            <div class="col-md-8">
              <%= @user.gender %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag :email %>
            </div>
            <div class="col-md-8">
              <%= @user.email %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag t('devise.passwords.address', default: 'Address') %><br />
            </div>
            <div class="col-md-8">
              <%= @user.address %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag t('devise.passwords.birth_date', default: 'Birthdate') %><br />
            </div>
            <div class="col-md-8">
              <%= @user.birthdate %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag :messages %><br />
            </div>
            <div class="col-md-8">
              <%= @user.all_by_author %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-4">
              <%= label_tag :likes %><br />
            </div>
            <div class="col-md-8">
              <%= @user.likes_count %>
            </div>
          </div>
          <div class="panel-body panel-body-bottom">
            <div class="col-md-4">
              <%= label_tag t('devise.passwords.registered_at', default: 'Registered at') %><br />
            </div>
            <div class="col-md-8">
              <%= @user.registered %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12">
      <%= render 'messages/all_topics', topics: @topics, chapter: @chapter, chapters: @chapters %>
    </div>
  </div>
</div>