config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :sections, except: [:new]
  resources :chapters, except: [:index, :new] do
    resources :topics, except: [:index]
  end
  resources :messages, except: [:show, :new]
  resources :likes, only: [:create]


  root 'sections#index'
  get 'admins/index'
  post 'users/create_user'
  match '*path', :to => 'application#routing_error', :via => [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :chapters, dependent: :destroy
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  include AdminsHelper

  before_action :authenticate_admin, only:[:edit, :update, :destroy]
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)
    respond_to do |format|
      if @section.save
        format.html { redirect_to admins_index_path, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: admins_index_url}
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      first_section_params = params.fetch(:section, {})
      second_section_params = {user_id: current_user.id, status: Constant::STATUS }
      first_section_params.merge(second_section_params).permit!
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :section_title, class: 'forum-title' %>
    <%= form.text_field :title, class: 'form-control-half' %>
    <%= form.submit class: 'btn btn-danger'%>
  </div>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>
      <ul>
        <% section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/sections/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Rails Forum', root_path, class: 'navbar-brand' %>
    </div>
    <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Users', users_path %></li>
        <% if user_admin? %>
          <li><%= link_to 'Administrating', admins_index_path %></li>
        <% end %>
        <li><%= link_to 'Last messages', messages_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to current_user do %>
            <span class="glyphicon glyphicon-user"></span> Profile
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span> Logout
          <% end %>
        </li>
      </ul>
    <%else%>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-user"></span> Sign Up
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span> Login
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/sections/_section_table.html.erb
<div class="forum-section">
  <table class="table">
    <thead class="forum-title">
    <tr>
      <th class="col-sm-7">
        <%= link_to section.title, section, class: 'forum-title' %>
        <% if user_admin? %>
          | <%= link_to 'Edit', edit_section_path(section), data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
          | <%= link_to 'Delete', section, method: :delete, data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
        <% end %>
      </th>
      <th class="col-sm-1">Topics</th>
      <th class="col-sm-1">Posts</th>
      <th class="col-sm-3">Last post</th>
    </tr>
    </thead>
    <tbody class="forum-section-white">
      <% section.chapters.each do |chapter| %>
        <tr>
          <td class="col-sm-7">
            <%= link_to chapter.title, chapter, class: 'chapter-head' %>
            <div class="chapter-description"><%= chapter.description %></div>
          </td>
          <td class="col-sm-1"><%= chapter.topics_count %></td>
          <td class="col-sm-1"><%= chapter.posts %></td>
          <td class="col-sm-3">
            <% last_post = chapter.last_post%>
            <div class="full-place">
              <%= link_to last_post[:topic_title], chapter_topic_path(chapter, last_post[:topic].id) if last_post[:topic]%>
            </div>
            <div class="full-place"><%=last_post[:message]%></div>
            <div class="full-place"><%= link_to last_post[:user_name], last_post[:user] if last_post[:user]%></div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sections/edit.html.erb
<div class="container">
  <h1>Edit Section</h1>
  <div class="forum-section">
    <div class="panel-body">
      <%= render 'form', section: @section %>
    </div>
  </div>
  <%= link_to 'Back', sections_path %>
</div>

app/views/sections/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <% @sections.each do |section| %>
      <%= render 'section_table', section: section %>
  <% end %>
</div>

app/views/sections/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <%= render 'section_table', section: @section %>
  <%= link_to 'Back', sections_path %>
</div>