config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :sections, except: [:new]
  resources :chapters, except: [:index, :new] do
    resources :topics, except: [:index]
  end
  resources :messages, except: [:show, :new]
  resources :likes, only: [:create]


  root 'sections#index'
  get 'admins/index'
  post 'users/create_user'
  match '*path', :to => 'application#routing_error', :via => [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :topics, dependent: :destroy

  # О! А вот и ассоциация :)
  def topics_count
    self.topics.count
  end

  # Снова ошибка в наименовании
  def posts
    messages.count
  end

  # Строго в сервис. Этот метод и все его зависимости. Модель не должна знать так много о других моделях
  def last_post
    last_message = last_chapter_message
    last_post_info = {message: last_message.try(:posted)}
    user_id = last_message.try(:user_id)
    topic = message_topic(last_message.topic_id) if last_message

    user = user_by_id(user_id) if user_id

    last_post_info[:user] = user
    last_post_info[:user_name] = user.try(:user_name)
    last_post_info[:topic_title] = topic.try(:title)
    last_post_info[:topic] = topic

    return last_post_info
  end

  private

  # User.find_by(id: user_id). Зачем свой метод?
  def user_by_id(user_id)
    User.find(user_id)
  end

  # Ассоциация?
  def messages
    Message.where(chapter_id: self.id)
  end

  def message_topic(id)
    Topic.find(id)
  end

  def last_chapter_message
    messages.order(created_at: :asc).last
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

  include AdminsHelper

  before_action :authenticate_admin, only:[:edit, :update, :destroy]
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  PAGINATION_LIMIT = 10.freeze

  def show
    topics = @chapter.topics
    # ActiveRecord в не должен просачиваться на уровень контролеера. Для этого есть named scopes.
    # Кроме того весь этот код неплохо смотрелся бы в сервисе.
    topics = topics.where('title like ?', "%#{params[:name]}%") if params[:name]
    @topics = topics.order(created_at: :desc).paginate(page: params[:page], per_page: PAGINATION_LIMIT)
  end

  def new
    @chapter = Chapter.new
  end

  def edit
    @sections = Section.all
  end

  # POST /chapters
  # POST /chapters.json

  # Я не совсем понимая зачем здесь ответ на два формата (html и json). В коде я нашел только обращения по html.
  # Как API это не сойдет, потому что:
  # * Нужна живая сессия для запроса
  # * API должно лежать в своем контроллере на другом роуте с версионированием. /api/v1/chapters_controller.rb
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      first_chapter_params = params.fetch(:chapter, {})
      second_chapter_params = {user_id: current_user.id, status: Constant::STATUS }
      first_chapter_params.merge(second_chapter_params).permit!
    end

end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_chapter_table.html.erb
<div class="forum-section">
  <table class="table">
    <thead class="forum-title">
    <tr>
      <th class="col-sm-7">
        <%= link_to chapter.title, chapter, class: 'forum-title' %>
        <% if user_admin? %>
          | <%= link_to 'Edit', edit_chapter_path(chapter), data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
          | <%= link_to 'Delete', chapter, method: :delete, data: { confirm: 'Are you sure?' }, class: 'forum-title' %>
        <% end %>
      </th>
      <th class="col-sm-1">Answers</th>
      <th class="col-sm-2">Autor</th>
      <th class="col-sm-2">Last post</th>
    </tr>
    </thead>
    <tbody class="forum-section-white">
      <% topics.each do |topic| %>
        <%= render 'topics/topic', topic: topic %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/chapters/_form.html.erb
<div class="panel-body-chapter">
  <%= form_with(model: chapter, local: true) do |form| %>
    <div class="form-group col-md-6">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :section %><br />
      <%= form.select(:section_id, sections.collect{ |p| [p.title, p.id] }, {autofocus: true}, class: 'form-control') %>
    </div>
    <div class="form-group col-md-12">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
    <% if chapter.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>
        <ul>
          <% chapter.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="actions">
      <%= form.submit class: 'btn btn-danger'%>
    </div>
  <% end %>
</div>

app/views/chapters/edit.html.erb
<div class="container">
  <h1>Edit Chapter</h1>
  <div class="forum-section">
      <%= render 'form', sections: @sections, chapter: @chapter %>
  </div>
  <%= link_to 'Back', sections_path %>
</div>

app/views/chapters/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
  <div class="col-sm-4">
    <form action="<%= chapter_path(@chapter.id) %>" method="get">
      <%= text_field_tag :name, params[:name] %>
      <%= submit_tag 'Name Filter', class: 'btn btn-default' %>
    </form>
  </div>
  <div class="col-sm-1 col-sm-offset-3">
    <%= link_to new_chapter_topic_path(@chapter.id), class: 'btn btn-default', role: 'button' do %>
      <span class="glyphicon glyphicon-plus"></span> New Topic
    <% end%>
  </div>
  <div class="col-sm-4">
    <div class="digg_pagination">
      <div class="page_info">
        <%= page_entries_info @topics %>
      </div>
      <%= will_paginate @topics, :container => false, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>
  <%= render 'chapter_table', chapter: @chapter, topics: @topics %>
  <%= link_to 'Back', sections_path %>
</div>